.TH clownf 1 "2020 Jan 13" Clownfish "Clownfish"
.SH NAME
clownf \- Management Commands for Lustre file systems.
.SH SYNOPSIS
.B clownf [\fIGROUP\fR] [\fICOMMAND\fR] [\fIARGS\fR] <\fFLAGS\fR>
.SH DESCRIPTION
.B clownf
(Clownfish) is a command chain that provides user-friendly solutions
for high availability features, installation, configuration, management,
monitoring and diagnosis of Lustre file system.
.PP
Please run \fBclownf --help\fR command to get more information.
.SH AUTHOR
The
.B clownf
command is part of the Clownfish package.
.SH SEE ALSO
.BR clownf_storage (1)
.BR clownf_agent (1)
.BR clownf_agent.service (5)
.BR consul.service (5)
