"""
Constants used in Clownfish
"""
from pycoral import constant
# DO NOT import any library that needs extra python package,
# since this might cause failure of commands that uses this
# library to install python packages.
CLOWNFISH_BUILD_LOG_DIR_BASENAME = "clownfish_build_log"

CLOWNF_CONFIG_FNAME = "clownfish.conf"
CLOWNF_CONFIG = constant.ETC_CORAL_DIR + "/" + CLOWNF_CONFIG_FNAME

CLF_LOG_DIR = constant.CORAL_LOG_DIR + "/clownf"
CLOWNF_TEST_LAUNCH_LOG_DIR = constant.CORAL_LOG_DIR + "/clownf_test_launch"

CLOWNFISH_TEST_LOG_DIR_BASENAME = "clownf_test"
CLOWNFISH_TEST_LOG_DIR = (constant.CORAL_LOG_DIR + "/" +
                          CLOWNFISH_TEST_LOG_DIR_BASENAME)

CLOWNFISH_DEFAULT_SERVER_PORT = 3002

CLF_CONSUL_SERVICE_PATH = "clownf_service"
CLF_CONSUL_HOST_PATH = "clownf_host"
CLF_CONSUL_CONFIG_KEY = "config"
CLF_CONSUL_LOCK_KEY = "lock"
CLF_MAX_WATCH_HOST = 5
CLF_MSG_ALREADY_STARTED = "Already started\n"


CLF_BACKFSTYPE = "backfstype"
CLF_BIND_ADDR = "bind_addr"
CLF_CLIENTS = "clients"
CLF_CONSUL = "consul"
CLF_DATACENTER = "datacenter"
CLF_DEVICE = "device"
CLF_DISABLED_HOSTS = "disabled_hosts"
CLF_DOMAIN_NAME = "domain_name"
CLF_ENCRYPT_KEY = "encrypt_key"
CLF_E2FSPROGS_RPM_DIR = "e2fsprogs_rpm_dir"
CLF_FILESYSTEMS = "filesystems"
CLF_FSNAME = "fsname"
CLF_FS_CLIENT = "fs_client"
CLF_FS_DISTRIBUTION_ID = "fs_distribution_id"
CLF_FS_DISTRIBUTIONS = "fs_distributions"
CLF_FS_RPM_DIR = "fs_rpm_dir"
CLF_FS_SERVER = "fs_server"
CLF_HOSTNAME = "hostname"
CLF_HOSTS = "hosts"
CLF_INDEX = "index"
CLF_INSTANCES = "instances"
CLF_IPMI = "ipmi"
CLF_IPMI_INTERFACE = "ipmi_interface"
CLF_IPMI_USERNAME = "ipmi_username"
CLF_IPMI_PASSWORD = "ipmi_password"
CLF_IPMI_HOSTNAME = "ipmi_hostname"
CLF_IPMI_PORT = "ipmi_port"
CLF_IS_MGS = "is_mgs"
CLF_LIBVIRT = "libvirt"
CLF_LIBVIRT_SERVER = "libvirt_server"
CLF_MDTS = "mdts"
CLF_MNT = "mnt"
CLF_MGS_ID = "mgs_id"
CLF_MGS_LIST = "mgs_list"
CLF_NID = "nid"
CLF_OSTS = "osts"
CLF_SERVERS = "servers"
CLF_SSH_IDENTITY_FILE = "ssh_identity_file"
CLF_STANDALONE = "standalone"
CLF_ZPOOL_NAME = "zpool_name"
CLF_ZPOOL_CREATE = "zpool_create"


# Dependent RPMs to be packaged into ISO for Clownfish installation
CLOWNF_DEPENDENT_RPMS = ["ipmitool"]

CLOWNF_FIELD_ACTIVE = "Active"
CLOWNF_FIELD_AGENT = "Agent"
CLOWNF_FIELD_AUTOSTART = "Autostart"
CLOWNF_FIELD_BACKFS_TYPE = "Backfs Type"
CLOWNF_FIELD_CLIENT = "Client"
CLOWNF_FIELD_CONSUL_ROLE = "Consul Role"
CLOWNF_FIELD_CONSUL_STATUS = "Consul Status"
CLOWNF_FIELD_CWATCHING_HOSTS = "CWatching Hosts"
CLOWNF_FIELD_CWATCHING_SERVICES = "CWatching Services"
CLOWNF_FIELD_DEVICE = "Device"
CLOWNF_FIELD_ENABLED = "Enabled"
CLOWNF_FIELD_ENABLED_HOSTS = "Enabled Hosts"
CLOWNF_FIELD_FSNAME = "FsName"
CLOWNF_FIELD_HEALTHY = "Healthy"
CLOWNF_FIELD_HOST = "Host"
CLOWNF_FIELD_HOST_SERVICE = "Host/Service"
CLOWNF_FIELD_LOAD_BALANCED = "Load Balanced"
CLOWNF_FIELD_LEADER = "Leader"
CLOWNF_FIELD_MOUNT_POINT = "Mount Point"
CLOWNF_FIELD_MOUNT_HOST = "Mount Host"
CLOWNF_FIELD_MOUNTED_CLIENTS = "Mounted Clients"
CLOWNF_FIELD_MOUNTED_SERVICES = "Mounted Services"
CLOWNF_FIELD_MOUNTED = "Mounted"
CLOWNF_FIELD_NAME = "Name"
CLOWNF_FIELD_OPERATING = "Operating"
CLOWNF_FIELD_SERVICE = "Service"
CLOWNF_FIELD_SERVER = "Server"
CLOWNF_FIELD_SYMMETRIC = "Symmetric"
CLOWNF_FIELD_WATCHER = "Watcher"
CLOWNF_FIELD_WATCHER_CANDIDATES = "Watcher Candidates"
CLOWNF_FIELD_WATCHER_HOST = "Watcher Host"
CLOWNF_FIELD_WATCHING = "Watching"
CLOWNF_FIELD_WATCHING_HOSTS = "Watching Hosts"
CLOWNF_FIELD_WATCHING_SERVICES = "Watching Services"
CLOWNF_FIELD_UP = "Up"

CLOWNF_VALUE_ACTIVE = "active"
CLOWNF_VALUE_ASYMMETRIC = "asymmetric"
CLOWNF_VALUE_AUTOSTART = "autostart"
CLOWNF_VALUE_BALANCED = "balanced"
CLOWNF_VALUE_CANDIDATE = "candidate"
CLOWNF_VALUE_CLIENT = "client"
CLOWNF_VALUE_DISABLED = "disabled"
CLOWNF_VALUE_DOWN = "down"
CLOWNF_VALUE_ENABLED = "enabled"
CLOWNF_VALUE_HOST = "host"
CLOWNF_VALUE_IDLE = "idle"
CLOWNF_VALUE_IMBALANCED = "imbalanced"
CLOWNF_VALUE_INACTIVE = "inactive"
CLOWNF_VALUE_LEADER = "leader"
CLOWNF_VALUE_LOCAL_MOUNTED = "local_mounted"
CLOWNF_VALUE_MEMBER = "member"
CLOWNF_VALUE_MOUNTED = "mounted"
CLOWNF_VALUE_NOT_AUTOSTART = "not_autostart"
CLOWNF_VALUE_NOT_WATCHING = "not_watching"
CLOWNF_VALUE_OPERATING = "operating"
CLOWNF_VALUE_OVERLOADED = "overloaded"
CLOWNF_VALUE_REMOTE_MOUNTED = "remote_mounted"
CLOWNF_VALUE_SERVER = "server"
CLOWNF_VALUE_SERVICE = "service"
CLOWNF_VALUE_SYMMETRIC = "symmetric"
CLOWNF_VALUE_UMOUNTED = "umounted"
CLOWNF_VALUE_UNDERLOADED = "underloaded"
CLOWNF_VALUE_UNKNOWN = "unknown"
CLOWNF_VALUE_UP = "up"
CLOWNF_VALUE_WATCHER = "watcher"
CLOWNF_VALUE_WATCHING = "watching"

CLOWNF_STDOUT_NOT_OPERATING = "Not operating"
CLOWNF_STDOUT_OPERATING = "Operating"
